// Modelli generici di partenza per quadro clinico, con esempi di esercizi.
// Vanno sempre rivisti, personalizzati e validati clinicamente: non sono
// un'indicazione automatica. Dato statico (non per-paziente): non serve nel database.
export const protocolLibrary = [

  // ---- RACHIDE ----
  {id:'cervicalgia', category:'Rachide', label:'Cervicalgia meccanica', text:
    'Mobilizzazione attiva del rachide cervicale entro il range tollerato (flesso-estensione, rotazioni lente), rinforzo dei flessori profondi del collo (chin tuck, tenuta isometrica 5x10\'\').\nCorrezione posturale (postazione lavoro/postura del capo), stretching della muscolatura ipertonica (trapezio superiore, elevatore della scapola) 3x30\'\' per lato.\nEsercizi di controllo motorio cervico-scapolare (attivazione trapezio inferiore/dentato anteriore) e rieducazione funzionale progressiva.'},
  {id:'colpo-frusta', category:'Rachide', label:'Colpo di frusta cervicale (whiplash)', text:
    'Fase acuta: rassicurazione, mobilizzazione attiva precoce e graduale entro il range indolore (rotazioni/inclinazioni lente da seduto), evitare immobilizzazione prolungata.\nFase subacuta: recupero ROM cervicale completo, rinforzo isometrico dei flessori profondi (chin tuck 5x10\'\'), esercizi propriocettivi cervicali (rieducazione oculo-cervicale: fissazione di un target mentre si muove il capo).\nFase funzionale: rinforzo isotonico progressivo del collo, ripresa graduale delle attività quotidiane/lavorative, monitorando eventuali sintomi associati (cefalea, vertigini).'},
  {id:'dorsalgia', category:'Rachide', label:'Dorsalgia meccanica', text:
    'Mobilizzazione del rachide dorsale (estensioni su foam roller, mobilizzazioni in rotazione da seduto) e della gabbia toracica, stretching dei pettorali in appoggio a parete 3x30\'\'.\nRinforzo dei muscoli estensori dorsali (superman a terra) e stabilizzatori scapolari (retrazioni scapolari con elastico), esercizi di respirazione toracica.\nCorrezione posturale (postura in ufficio/attività lavorativa) e rieducazione funzionale progressiva.'},
  {id:'lombalgia-aspecifica', category:'Rachide', label:'Lombalgia aspecifica', text:
    'Educazione del paziente su decorso benigno e importanza del movimento (evitare riposo prolungato), esercizi di mobilità lombare (cat-camel, bacino in flesso-estensione).\nCore stability: bird-dog 3x8 per lato, bridging (ponte gluteo) 3x12, plank progressivo; rinforzo della muscolatura estensoria (superman) e addominale.\nProgressione verso attività funzionali quotidiane e, se presente, verso il gesto sportivo specifico (squat, hinge/stacco), monitorando la risposta sintomatica.'},
  {id:'lombosciatalgia', category:'Rachide', label:'Lombosciatalgia / ernia discale (approccio conservativo)', text:
    'Fase acuta: posizioni antalgiche (es. decubito con anche/ginocchia flesse), mobilizzazione controllata (cat-camel), educazione su gestione del carico e decorso atteso.\nFase subacuta: esercizi di stabilizzazione lombare (bird-dog, bridging), mobilizzazione neurale del nervo sciatico (slider in scivolamento) se indicata e tollerata, rinforzo progressivo.\nFase funzionale: recupero delle attività quotidiane, rinforzo globale (squat, hip hinge con carico progressivo), monitoraggio dei sintomi neurologici (parestesie, deficit di forza) per eventuale rivalutazione medica.'},
  {id:'stenosi-lombare', category:'Rachide', label:'Stenosi del canale lombare', text:
    'Esercizi in flessione lombare (posizione antalgica tipica: bacino in retroversione da seduto/supino, child\'s pose), rinforzo della muscolatura addominale e stabilizzatrice (dead bug).\nCondizionamento aerobico a basso impatto (cyclette con manubrio alto, deambulazione con tolleranza al carico), stretching dei flessori d\'anca (affondo con retroversione del bacino) 3x30\'\'.\nEducazione alla gestione dei sintomi da claudicatio neurogena e alla ripresa graduale del cammino (intervalli con pause programmate).'},
  {id:'scoliosi', category:'Rachide', label:'Scoliosi — approccio conservativo', text:
    'Valutazione posturale e della curva, esercizi asimmetrici di correzione attiva secondo principi di rieducazione posturale specifica (es. tipo Schroth, se formazione specifica disponibile).\nRinforzo della muscolatura paravertebrale e del core (plank, bird-dog) e del core, esercizi respiratori orientati alla curva (respirazione nella concavità).\nMonitoraggio periodico dell\'evoluzione della curva in collaborazione con lo specialista di riferimento.'},

  // ---- SPALLA E ARTO SUPERIORE ----
  {id:'spalla-conflitto', category:'Spalla', label:'Conflitto subacromiale', text:
    'Fase acuta: controllo del dolore, mobilizzazione passiva/pendolare (Codman) entro il range tollerato, correzione posturale del cingolo scapolare.\nFase di rinforzo: attivazione cuffia dei rotatori (extrarotatori con elastico a gomito addotto 3x15), rinforzo dei muscoli stabilizzatori della scapola (trapezio inferiore: Y a terra; dentato anteriore: push-up plus 3x10).\nFase funzionale: rinforzo progressivo in elevazione (alzate laterali/frontali a basso carico), esercizi eccentrici, ritorno al gesto lavorativo/sportivo specifico (overhead).'},
  {id:'capsulite-adesiva', category:'Spalla', label:'Capsulite adesiva (spalla congelata)', text:
    'Fase di congelamento (dolorosa): mobilizzazione delicata entro il range tollerato (pendolari di Codman), gestione del dolore, evitare stiramenti aggressivi.\nFase di rigidità: mobilizzazione articolare progressiva (stretching capsulare: scivolamento su tavolo, wall walk/scalata al muro), esercizi attivi-assistiti con bastone in tutti i piani.\nFase di scongelamento: recupero del ROM completo, rinforzo funzionale progressivo della cuffia dei rotatori (elastico) e del cingolo scapolare.'},
  {id:'cuffia-rotatori', category:'Spalla', label:'Lesione cuffia dei rotatori (conservativo/post-chirurgico)', text:
    'Fase protetta: immobilizzazione secondo indicazione, mobilizzazione passiva controllata (pendolari), controllo del dolore e dell\'infiammazione.\nFase attiva: mobilizzazione attiva-assistita con bastone, rinforzo isometrico progressivo della cuffia (extra/intrarotazione a gomito bloccato), riattivazione scapolare.\nFase di rinforzo: rinforzo isotonico progressivo con elastico/manubri leggeri, esercizi eccentrici, ritorno graduale ai gesti sportivi/lavorativi sopra la testa.'},
  {id:'instabilita-spalla', category:'Spalla', label:'Instabilità di spalla (cronica/microinstabilità)', text:
    'Rinforzo della cuffia dei rotatori (extrarotatori con elastico) e dei muscoli stabilizzatori scapolari, esercizi propriocettivi in catena chiusa (plank su superficie instabile, quadrupedia con perturbazioni).\nProgressione verso esercizi in range a rischio (abduzione-extrarotazione) solo con adeguato controllo motorio, rinforzo eccentrico degli extrarotatori.\nLavoro funzionale specifico per lo sport/attività, educazione sui segnali di instabilità da monitorare.'},
  {id:'lussazione-spalla', category:'Spalla', label:'Lussazione di spalla (episodio acuto, post-riduzione)', text:
    'Fase di protezione (0-2 sett.): tutore secondo indicazione medica, mobilizzazione passiva del gomito/polso/mano per evitare rigidità a distanza, isometrie della cuffia a basso carico entro range protetto.\nFase di recupero ROM (2-6 sett.): mobilizzazione attiva-assistita con bastone evitando l\'associazione abduzione+extrarotazione (posizione a rischio), rinforzo isometrico progressivo di cuffia dei rotatori e stabilizzatori scapolari.\nFase di rinforzo e ritorno allo sport (6+ sett.): rinforzo isotonico ed eccentrico della cuffia, lavoro propriocettivo (plank su superficie instabile), reintroduzione molto graduale dei gesti overhead/di contatto solo con controllo motorio adeguato ed eventuale tutore funzionale.'},

  // ---- GOMITO, POLSO E MANO ----
  {id:'epicondilite', category:'Gomito, polso e mano', label:'Epicondilite laterale (gomito del tennista)', text:
    'Fase acuta: gestione del carico (riduzione attività aggravanti), stretching dei muscoli estensori del polso (gomito esteso, polso in flessione) 3x30\'\', terapia manuale locale.\nFase di rinforzo: esercizi eccentrici progressivi per gli estensori del polso (con manubrio leggero/elastico, 3x15 lenti in fase eccentrica), rinforzo della presa (hand grip).\nFase funzionale: ripresa graduale del gesto lavorativo/sportivo, valutazione ergonomica dell\'attività scatenante (es. impugnatura racchetta).'},
  {id:'epitrocleite', category:'Gomito, polso e mano', label:'Epitrocleite (gomito del golfista)', text:
    'Gestione del carico e stretching dei flessori del polso e pronatori (gomito esteso, polso in estensione) 3x30\'\', terapia manuale locale.\nRinforzo eccentrico progressivo dei flessori del polso (manubrio leggero, 3x15) e pronatori, rinforzo della presa.\nRipresa graduale del gesto sportivo/lavorativo con eventuale correzione tecnica.'},
  {id:'tunnel-carpale', category:'Gomito, polso e mano', label:'Sindrome del tunnel carpale (conservativo)', text:
    'Educazione posturale ed ergonomica del polso, eventuale tutore notturno, mobilizzazione neurale del nervo mediano (slider) se tollerata.\nStretching e mobilizzazione dei tessuti del polso e dell\'avambraccio (mobilizzazione tendinea in flesso-estensione delle dita).\nRinforzo progressivo della mano (hand grip a bassa resistenza), monitoraggio dei sintomi neurologici (parestesie, deficit di forza del pollice) per eventuale rivalutazione medica.'},
  {id:'de-quervain', category:'Gomito, polso e mano', label:'Tendinopatia di De Quervain', text:
    'Gestione del carico (riduzione dei movimenti ripetuti di presa/pollice), eventuale tutore di riposo.\nMobilizzazione e stretching dei tendini abduttore lungo ed estensore breve del pollice (stretching tipo Finkelstein assistito, delicato) 3x20\'\'.\nRinforzo progressivo (presa a pinza con elastico) e graduale ripresa delle attività manuali.'},
  {id:'rizoartrosi', category:'Gomito, polso e mano', label:'Rizoartrosi (artrosi trapezio-metacarpale)', text:
    'Educazione alla protezione articolare e alla modifica delle attività che sovraccaricano il pollice.\nMobilizzazione delicata (opposizione del pollice), rinforzo della muscolatura intrinseca della mano (pinch/presa a pinza leggera), eventuale tutore funzionale.\nAdattamento delle attività quotidiane e lavorative, gestione dei periodi di riacutizzazione.'},
  {id:'lussazione-dito', category:'Gomito, polso e mano', label:'Lussazione/distorsione di dito (interfalangea)', text:
    'Fase di protezione (0-2 sett.): sindattilia (bendaggio al dito adiacente) o tutore secondo indicazione medica, crioterapia, mobilizzazione delle articolazioni non coinvolte.\nFase di recupero ROM: mobilizzazione attiva progressiva in flesso-estensione, delicata mobilizzazione passiva se rigidità residua.\nFase funzionale: rinforzo della presa (putty/pallina antistress), ripresa graduale del gesto sportivo con eventuale bendaggio funzionale/buddy taping.'},

  // ---- ANCA ----
  {id:'coxartrosi', category:'Anca', label:'Coxartrosi', text:
    'Mobilizzazione articolare nei range non dolorosi, rinforzo di abduttori (clamshell, abduzione in laterale) ed estensori d\'anca (ponte gluteo), esercizi in scarico parziale (cyclette, idrokinesiterapia se disponibile).\nRinforzo progressivo a catena cinetica chiusa (squat parziale, step-up basso), lavoro sull\'equilibrio (appoggio monopodalico assistito) e sul cammino, gestione del carico secondo la sintomatologia.'},
  {id:'conflitto-femoro-acetabolare', category:'Anca', label:'Conflitto femoro-acetabolare', text:
    'Gestione del carico e degli angoli articolari sintomatici, mobilizzazione controllata dell\'anca (mobilizzazione in flessione/rotazione entro range indolore).\nRinforzo della muscolatura stabilizzatrice del bacino e dell\'anca (glutei: ponte gluteo, clamshell; core: dead bug), controllo motorio del movimento (squat con controllo del valgismo).\nProgressione funzionale verso il gesto sportivo, evitando i range di massima flessione/rotazione se sintomatici.'},
  {id:'borsite-trocanterica', category:'Anca', label:'Borsite trocanterica / tendinopatia dei glutei', text:
    'Gestione del carico (evitare posizioni in compressione laterale prolungata, es. decubito sul lato affetto), terapia manuale locale.\nRinforzo progressivo isometrico (abduzione isometrica a muro 5x30\'\') e poi isotonico degli abduttori d\'anca (clamshell con elastico, step-down laterale), correzione del pattern del passo.\nRipresa graduale delle attività, con attenzione al carico in appoggio monopodalico (single-leg bridge).'},
  {id:'protesi-anca', category:'Anca', label:'Post-chirurgico — protesi d\'anca', text:
    'Fase precoce: mobilizzazione protetta secondo le precauzioni chirurgiche (via di accesso), rinforzo isometrico (quadricipite, gluteo), verticalizzazione e cammino assistito con ausili.\nFase intermedia: recupero del ROM funzionale, rinforzo progressivo di glutei (ponte gluteo, clamshell) e stabilizzatori, correzione dello schema del passo.\nFase avanzata: rinforzo funzionale (step-up, mini-squat), equilibrio, ripresa delle attività quotidiane e, se indicato, di attività sportive a basso impatto.'},
  {id:'contusione-anca-coscia', category:'Anca', label:'Contusione dell\'anca/coscia (ematoma da impatto diretto)', text:
    'Fase acuta (0-72h): protezione dal carico eccessivo, crioterapia, mobilizzazione attiva delicata entro il range indolore per prevenire la miosite ossificante.\nFase subacuta: recupero progressivo del ROM (flessione del ginocchio da prono se coinvolge il quadricipite prossimale), rinforzo isometrico poi isotonico graduale.\nFase funzionale: stretching graduale, rinforzo eccentrico, test funzionali (squat, affondo, corsa) prima del rientro sportivo, monitorando la comparsa di indurimento/dolore persistente (segnale di allarme per miosite ossificante).'},

  // ---- GINOCCHIO ----
  {id:'ginocchio-lca', category:'Ginocchio', label:'Post-chirurgico — LCA/menisco', text:
    'Fase iniziale (0-3 sett.): controllo edema (crioterapia, elevazione), mobilizzazione passiva e attiva-assistita entro il ROM concesso, attivazione isometrica del quadricipite (contrazioni statiche, straight leg raise), carico progressivo secondo indicazione chirurgica.\nFase intermedia (4-8 sett.): recupero ROM completo, rinforzo progressivo catena estensoria/flessoria (leg press, curl femorale), esercizi a catena cinetica chiusa (mini-squat, step-up), propriocezione su superfici stabili (appoggio monopodalico).\nFase avanzata (9+ sett.): rinforzo funzionale, lavoro pliometrico graduale (salti bipodalici poi monopodalici), gesto sport-specifico, test di ritorno all\'attività (hop test) prima del rientro agonistico.'},
  {id:'gonartrosi', category:'Ginocchio', label:'Gonartrosi', text:
    'Mobilizzazione articolare nei range non dolorosi, rinforzo del quadricipite (isometrico a 60° poi isotonico con leg extension/leg press) e della catena posteriore (curl femorale).\nEsercizi in scarico parziale (cyclette, idrokinesiterapia se disponibile), gestione del peso corporeo se rilevante.\nRinforzo progressivo funzionale (mini-squat, step-up basso), lavoro sull\'equilibrio e sul cammino, gestione dei periodi di riacutizzazione.'},
  {id:'condropatia-femoro-rotulea', category:'Ginocchio', label:'Condropatia/sindrome femoro-rotulea', text:
    'Gestione del carico (riduzione temporanea delle attività aggravanti come scale/squat profondo), rinforzo del quadricipite (VMO in particolare: leg extension in ultimo arco, terminal knee extension con elastico).\nRinforzo della catena cinetica prossimale (glutei: clamshell, ponte monopodalico; stabilizzatori d\'anca), correzione del pattern di movimento in squat/affondo (controllo del valgismo dinamico).\nProgressione graduale verso attività funzionali e sportive, monitorando la risposta sintomatica.'},
  {id:'tendinopatia-rotulea', category:'Ginocchio', label:'Tendinopatia rotulea (ginocchio del saltatore)', text:
    'Gestione del carico (riduzione attività pliometriche), esercizi isometrici per il controllo del dolore in fase acuta (squat isometrico a 60° 5x45\'\').\nProgressione a esercizi isotonici e poi eccentrici (decline squat su piano inclinato 3x15) per il tendine rotuleo.\nReintroduzione graduale di salti e attività sport-specifiche con monitoraggio del carico e della sintomatologia.'},
  {id:'protesi-ginocchio', category:'Ginocchio', label:'Post-chirurgico — protesi di ginocchio', text:
    'Fase precoce: controllo edema e dolore, mobilizzazione precoce per il recupero del ROM (flessione/estensione assistita, scivolamento del tallone), attivazione del quadricipite (isometrie), verticalizzazione.\nFase intermedia: recupero del ROM funzionale, rinforzo progressivo (leg press, mini-squat), normalizzazione dello schema del passo.\nFase avanzata: rinforzo funzionale (step-up), equilibrio, ripresa delle attività quotidiane.'},
  {id:'lussazione-rotula', category:'Ginocchio', label:'Lussazione di rotula (prima lussazione/post-riduzione)', text:
    'Fase di protezione (0-3 sett.): tutore/ginocchiera con stabilizzazione rotulea secondo indicazione, controllo edema (crioterapia), isometrie del quadricipite (VMO), mobilizzazione della rotula in senso latero-mediale delicata.\nFase di recupero (3-6 sett.): recupero ROM progressivo, rinforzo del VMO (terminal knee extension, leg extension in ultimo arco), rinforzo dei glutei per il controllo del valgismo dinamico (clamshell, ponte monopodalico).\nFase funzionale (6+ sett.): rinforzo a catena chiusa (mini-squat con controllo dell\'allineamento), lavoro propriocettivo, reintroduzione graduale di corsa/cambi di direzione, eventuale tutore funzionale nel ritorno allo sport.'},
  {id:'contusione-ginocchio', category:'Ginocchio', label:'Contusione al ginocchio', text:
    'Fase acuta (0-72h): crioterapia, scarico parziale se necessario, mobilizzazione attiva delicata entro il range indolore per mantenere l\'escursione articolare.\nFase subacuta: recupero progressivo del ROM completo, rinforzo isometrico del quadricipite, mobilizzazione dei tessuti molli se presente ematoma organizzato.\nFase funzionale: rinforzo isotonico progressivo, ripresa graduale della corsa e dei cambi di direzione secondo tollerabilità.'},

  // ---- CAVIGLIA E PIEDE ----
  {id:'caviglia-distorsione', category:'Caviglia e piede', label:'Distorsione di caviglia', text:
    'Fase acuta: controllo edema (crioterapia, elevazione, bendaggio), mobilizzazione precoce protetta (alfabeto con la punta del piede), carico progressivo secondo tollerabilità.\nFase di rinforzo: propriocezione precoce su tavolette instabili/cuscino propriocettivo (appoggio monopodalico), rinforzo dei muscoli peronei ed evertori (elastico in eversione 3x15).\nFase funzionale: lavoro su cambi di direzione, salti (bipodalici poi monopodalici) e gesto sport-specifico prima del rientro in campo.'},
  {id:'lussazione-caviglia', category:'Caviglia e piede', label:'Lussazione di caviglia (post-riduzione/post-immobilizzazione)', text:
    'Fase di protezione: rispetto dei tempi di immobilizzazione/carico indicati dal chirurgo/ortopedico, mobilizzazione delle dita e della catena cinetica non immobilizzata, isometrie della muscolatura di gamba.\nFase di recupero ROM (a rimozione tutore): mobilizzazione attiva progressiva in flesso-estensione/eversione-inversione, mobilizzazione dei tessuti cicatriziali, recupero della deambulazione con carico progressivo.\nFase funzionale: rinforzo dei peronei ed evertori (elastico), propriocezione avanzata su superfici instabili, reintroduzione molto graduale di corsa e cambi di direzione con monitoraggio della stabilità articolare.'},
  {id:'tendinopatia-achillea', category:'Caviglia e piede', label:'Tendinopatia achillea', text:
    'Gestione del carico (riduzione temporanea di corsa/salti), esercizi isometrici per il controllo del dolore in fase acuta (sollevamento sui talloni isometrico 5x30\'\').\nProgressione a esercizi eccentrici (heel-drop su gradino, 3x15) per il tendine d\'Achille, stretching del tricipite surale se tollerato 3x30\'\'.\nReintroduzione graduale della corsa e del gesto sportivo, monitorando carico e sintomatologia.'},
  {id:'fascite-plantare', category:'Caviglia e piede', label:'Fascite plantare', text:
    'Gestione del carico, stretching della fascia plantare (con asciugamano/bottiglia sotto il piede) e del tricipite surale, eventuale plantare/tutore notturno.\nRinforzo della muscolatura intrinseca del piede (short foot, raccolta asciugamano con le dita), esercizi di mobilità della caviglia.\nRipresa graduale della deambulazione/corsa, valutazione della calzatura e della superficie di allenamento.'},
  {id:'contusione-piede', category:'Caviglia e piede', label:'Contusione al piede/caviglia', text:
    'Fase acuta: crioterapia, scarico parziale se necessario, mobilizzazione attiva delicata delle dita e della caviglia entro il range indolore.\nFase subacuta: recupero progressivo del carico e della deambulazione, mobilizzazione dei tessuti molli.\nFase funzionale: rinforzo progressivo, ripresa graduale della corsa secondo tollerabilità.'},

  // ---- MUSCOLARE E TENDINEO ----
  {id:'lesione-muscolare', category:'Muscolare e tendineo', label:'Lesione muscolare generica (stiramento/strappo)', text:
    'Fase acuta (0-72h): protezione, controllo del carico e dell\'edema (crioterapia), mobilizzazione precoce delicata entro il range indolore.\nFase subacuta: recupero progressivo della mobilità (stretching leggero), rinforzo isometrico poi isotonico, stretching graduale.\nFase funzionale: rinforzo eccentrico, esercizi propriocettivi e pliometrici, test funzionali (sprint, cambio di direzione) prima del rientro sportivo.'},
  {id:'strappo-quadricipite', category:'Muscolare e tendineo', label:'Strappo/stiramento del quadricipite', text:
    'Fase acuta (0-72h): protezione e scarico parziale, crioterapia, mobilizzazione delicata in flessione di ginocchio entro range indolore (evitare stretching aggressivo nelle prime 72h).\nFase subacuta: recupero progressivo del ROM, rinforzo isometrico del quadricipite (isometria a 60-90°) poi isotonico a basso carico (leg extension parziale), stretching graduale da proni.\nFase funzionale: rinforzo eccentrico (nordic-like per quadricipite/affondi controllati), progressione a corsa lineare, accelerazioni, cambi di direzione e sprint prima del rientro sportivo.'},
  {id:'strappo-ischiocrurali', category:'Muscolare e tendineo', label:'Strappo bicipite femorale / ischiocrurali (hamstring)', text:
    'Fase acuta (0-72h): protezione dal carico, crioterapia, mobilizzazione delicata entro range indolore (evitare stiramento aggressivo).\nFase subacuta: rinforzo isometrico progressivo (ponte a una gamba isometrico), stretching leggero, introduzione di esercizi eccentrici a basso carico (leg curl lento) quando tollerato.\nFase funzionale: rinforzo eccentrico progressivo (nordic hamstring curl, stiff-leg deadlift a carico crescente), lavoro di velocità/sprint progressivo, test funzionali prima del rientro sportivo (fondamentale per ridurre il rischio di recidiva, molto frequente in questa sede).'},
  {id:'strappo-adduttori', category:'Muscolare e tendineo', label:'Strappo degli adduttori', text:
    'Fase acuta (0-72h): protezione, crioterapia, mobilizzazione delicata entro range indolore, evitare movimenti in abduzione/rotazione ampia.\nFase subacuta: rinforzo isometrico degli adduttori (squeeze con palla tra le ginocchia 5x10\'\'), stretching leggero, rinforzo del core.\nFase funzionale: rinforzo isotonico ed eccentrico progressivo (copenhagen adduction a progressione di leva), reintroduzione graduale di sprint e cambi di direzione, test funzionali prima del rientro sportivo.'},
  {id:'strappo-polpaccio', category:'Muscolare e tendineo', label:'Strappo del gastrocnemio/polpaccio ("tennis leg")', text:
    'Fase acuta (0-72h): protezione dal carico (eventuale utilizzo di talloniera/rialzo, stampelle se necessario), crioterapia, mobilizzazione delicata della caviglia entro range indolore.\nFase subacuta: rinforzo isometrico del tricipite surale (sollevamento sui talloni isometrico parziale), stretching molto graduale, recupero progressivo del carico.\nFase funzionale: rinforzo eccentrico (heel-drop), progressione a camminata veloce, corsa e sprint, test funzionali (salti, cambi di ritmo) prima del rientro sportivo.'},
  {id:'contusione-muscolare', category:'Muscolare e tendineo', label:'Contusione muscolare (da impatto diretto)', text:
    'Fase acuta (0-72h): protezione dal carico eccessivo, crioterapia, mobilizzazione attiva delicata entro il range indolore per prevenire rigidità e miosite ossificante (evitare stretching aggressivo e massaggio profondo precoce).\nFase subacuta: recupero progressivo del ROM, rinforzo isometrico poi isotonico graduale, mobilizzazione dei tessuti se ematoma organizzato.\nFase funzionale: stretching graduale, rinforzo eccentrico, test funzionali prima del rientro sportivo, monitorando indurimento/dolore persistente.'},
  {id:'pubalgia', category:'Muscolare e tendineo', label:'Pubalgia (sindrome retto-adduttoria)', text:
    'Gestione del carico (riduzione di sprint/cambi di direzione), rinforzo isometrico degli adduttori (squeeze con palla) e della parete addominale (dead bug, plank).\nRinforzo progressivo isotonico di adduttori (copenhagen adduction) e core, lavoro di controllo motorio del bacino.\nProgressione verso gesti sport-specifici (corsa, cambi di direzione) con carico graduale.'},
  {id:'doms-sovraccarico', category:'Muscolare e tendineo', label:'Sovraccarico funzionale / DOMS', text:
    'Gestione del carico allenante, mobilizzazione attiva leggera, tecniche di recupero (stretching dolce, lavoro aerobico blando come camminata/cyclette a bassa intensità).\nRipresa progressiva del programma di allenamento abituale, monitorando il recupero tra le sedute.'},

  // ---- ALTRO MUSCOLO-SCHELETRICO ----
  {id:'osteoporosi', category:'Altro muscolo-scheletrico', label:'Osteoporosi — esercizio terapeutico', text:
    'Esercizi di rinforzo muscolare progressivo con carico (squat, step-up, secondo tollerabilità e indicazione medica), esercizi in carico per la densità ossea (cammino con sovraccarico, salti a basso impatto se indicato).\nEsercizi di equilibrio e prevenzione delle cadute (appoggio monopodalico, tandem stance), educazione posturale (evitare flessioni del rachide sotto carico).\nCondizionamento aerobico a basso impatto, monitoraggio del dolore e della tollerabilità al carico.'},
  {id:'fibromialgia', category:'Altro muscolo-scheletrico', label:'Fibromialgia — esercizio terapeutico', text:
    'Educazione sul dolore cronico e sull\'importanza dell\'attività fisica graduale, esercizio aerobico a basso impatto (es. cammino, acqua) partendo da bassa intensità/durata.\nRinforzo muscolare leggero e progressivo (esercizi a corpo libero, bande elastiche leggere), tecniche di rilassamento e gestione dello stress (respirazione diaframmatica).\nProgressione molto graduale del carico, monitorando attentamente la risposta sintomatica per evitare riacutizzazioni.'},
  {id:'contusione-ossea', category:'Altro muscolo-scheletrico', label:'Contusione ossea/periostea', text:
    'Fase acuta: protezione dal carico diretto sulla zona, crioterapia, mobilizzazione attiva delle articolazioni limitrofe entro range indolore.\nFase subacuta: recupero progressivo del carico e della funzione, rinforzo isometrico poi isotonico graduale.\nFase funzionale: ripresa graduale delle attività, monitorando la risoluzione del dolore alla palpazione e al carico.'},

  // ---- NEUROLOGICO ----
  {id:'ictus', category:'Neurologico', label:'Emiparesi post-ictus', text:
    'Fase acuta/subacuta: mobilizzazione precoce, prevenzione delle complicanze da immobilità, facilitazione del controllo motorio del lato colpito.\nRieducazione del cammino e dell\'equilibrio, esercizi task-oriented per il recupero funzionale dell\'arto superiore e inferiore.\nRinforzo progressivo, lavoro sulla componente cognitivo-motoria, adattamento dell\'ambiente domestico secondo necessità.'},
  {id:'parkinson', category:'Neurologico', label:'Malattia di Parkinson', text:
    'Esercizi per l\'ampiezza del movimento (approccio tipo "big movements"), lavoro sul cammino con attenzione a lunghezza del passo e freezing.\nEsercizi di equilibrio e prevenzione delle cadute, mobilità del tronco e rinforzo posturale.\nAttività aerobica regolare, stimolazione con cue esterni (visivi/uditivi) per facilitare l\'avvio del movimento.'},
  {id:'sclerosi-multipla', category:'Neurologico', label:'Sclerosi multipla', text:
    'Valutazione della fatica e adattamento del carico di lavoro (principio di conservazione dell\'energia), esercizi di rinforzo e mobilità secondo tollerabilità.\nRieducazione dell\'equilibrio e del cammino, gestione della spasticità con stretching e mobilizzazione.\nAttività aerobica a intensità controllata, monitoraggio attento della fatica e dei sintomi neurologici.'},
  {id:'lesione-midollare', category:'Neurologico', label:'Lesione midollare (para/tetraplegia)', text:
    'Mantenimento del ROM articolare e prevenzione delle retrazioni, rinforzo della muscolatura residua funzionale.\nAddestramento ai trasferimenti e all\'uso della carrozzina, verticalizzazione se indicata.\nRieducazione funzionale mirata al massimo grado di autonomia possibile, in stretta collaborazione con l\'équipe riabilitativa.'},
  {id:'guillain-barre', category:'Neurologico', label:'Sindrome di Guillain-Barré (fase di recupero)', text:
    'Mobilizzazione passiva/attiva-assistita graduale, prevenzione delle retrazioni articolari nella fase di recupero.\nRinforzo muscolare progressivo molto graduale, evitando l\'affaticamento eccessivo (rischio di sovraccarico in fase di recupero).\nRieducazione funzionale del cammino e delle attività quotidiane, progressione secondo il recupero neurologico individuale.'},
  {id:'vertigini-vestibolare', category:'Neurologico', label:'Vertigini / disturbi vestibolari (incl. VPPB)', text:
    'Se indicato dal quadro clinico, manovre liberatorie per la vertigine parossistica posizionale (solo se di specifica competenza/formazione).\nEsercizi di riabilitazione vestibolare: adattamento oculo-cervicale, esercizi di abitudine ai movimenti scatenanti, esercizi di equilibrio.\nProgressione graduale dell\'esposizione ai movimenti che scatenano i sintomi, monitorando la tollerabilità.'},
  {id:'paralisi-facciale', category:'Neurologico', label:'Paralisi del nervo facciale (facial palsy)', text:
    'Educazione e protezione dell\'occhio se presente lagoftalmo, massaggio facciale delicato e mobilizzazione precoce.\nEsercizi di attivazione neuromuscolare selettiva davanti allo specchio (biofeedback visivo), evitando sincinesie da sforzo eccessivo.\nProgressione molto graduale, monitorando la comparsa di movimenti associati indesiderati (sincinesie).'},
  {id:'neuropatia-periferica', category:'Neurologico', label:'Polineuropatia periferica (es. diabetica)', text:
    'Educazione alla protezione della sensibilità cutanea (controllo dei piedi, calzature adeguate), mobilizzazione articolare regolare.\nEsercizi di rinforzo muscolare e di equilibrio per compensare il deficit propriocettivo, prevenzione delle cadute.\nCondizionamento aerobico a basso impatto secondo tollerabilità, monitoraggio della sensibilità periferica.'},

  // ---- LINFATICO ----
  {id:'linfedema-secondario', category:'Linfatico', label:'Linfedema secondario (post-chirurgico/oncologico)', text:
    'Valutazione della circonferenza dell\'arto e delle condizioni della cute, drenaggio linfatico manuale con tecnica specifica.\nBendaggio multistrato a bassa elasticità o indumento compressivo su misura, esercizi decongestionanti a bassa intensità eseguiti a arto bendato/compresso.\nEducazione alla cura della cute e alla prevenzione delle infezioni, autogestione a lungo termine (autodrenaggio, attività fisica adattata, indumento compressivo).'},
  {id:'linfedema-primario', category:'Linfatico', label:'Linfedema primario', text:
    'Valutazione volumetrica dell\'arto interessato, drenaggio linfatico manuale e terapia decongestiva combinata.\nBendaggio/indumento compressivo adeguato al grado di edema, esercizi in compressione per favorire il drenaggio.\nProgramma di mantenimento a lungo termine con indumento elastocompressivo ed educazione all\'autogestione quotidiana.'},
  {id:'edema-post-chirurgico', category:'Linfatico', label:'Edema post-chirurgico/post-traumatico (insufficienza veno-linfatica)', text:
    'Gestione posturale (elevazione dell\'arto), pompa muscolare attiva della caviglia/polpaccio, mobilizzazione precoce secondo tollerabilità.\nApplicazione di bendaggio o calza elastocompressiva se indicato, crioterapia nella fase acuta.\nProgressione del carico e della deambulazione monitorando l\'andamento dell\'edema.'},

  // ---- RESPIRATORIO ----
  {id:'bpco', category:'Respiratorio', label:'BPCO — riabilitazione respiratoria', text:
    'Tecniche di disostruzione bronchiale, controllo del respiro (respirazione diaframmatica, espirazione a labbra socchiuse).\nRiallenamento allo sforzo aerobico a intensità controllata (cammino, cicloergometro), rinforzo della muscolatura periferica (arti superiori e inferiori).\nEducazione alla gestione della dispnea nelle attività quotidiane e al riconoscimento dei segnali di riacutizzazione.'},
  {id:'post-covid', category:'Respiratorio', label:'Sindrome post-COVID / esiti respiratori', text:
    'Rieducazione respiratoria progressiva, gestione della fatica secondo il principio del pacing (alternanza attività-riposo).\nRiallenamento allo sforzo molto graduale, partendo da bassa intensità, con progressione guidata dalla tollerabilità sintomatica.\nMonitoraggio di saturazione, frequenza cardiaca e sintomi da sforzo (dispnea, fatica), coordinamento con il medico curante in caso di segnali d\'allarme.'},
  {id:'post-chirurgia-toracica', category:'Respiratorio', label:'Riabilitazione post-chirurgia toracica/addominale maggiore', text:
    'Mobilizzazione precoce, esercizi di espansione polmonare e tecniche di disostruzione bronchiale.\nControllo del dolore (anche posturale, con supporto di un cuscino sulla ferita) per favorire una tosse efficace.\nRipresa progressiva della deambulazione e delle attività quotidiane, monitorando la funzione respiratoria.'},

  // ---- VASCOLARE ----
  {id:'arteriopatia-periferica', category:'Vascolare', label:'Arteriopatia periferica (claudicatio intermittens)', text:
    'Programma di cammino strutturato a intervalli (cammino fino a comparsa del dolore, breve recupero, ripetizione), sotto supervisione.\nEducazione ai fattori di rischio cardiovascolare, rinforzo della muscolatura degli arti inferiori.\nMonitoraggio della distanza di cammino nel tempo come indicatore di progresso, in coordinamento con il medico curante.'},
  {id:'trombosi-venosa-esiti', category:'Vascolare', label:'Esiti di trombosi venosa profonda', text:
    'Mobilizzazione precoce secondo indicazione medica, utilizzo di calza elastocompressiva.\nEsercizi di pompa muscolare del polpaccio, graduale ripresa del carico e della deambulazione.\nMonitoraggio di eventuali segni di sindrome post-trombotica (edema, pesantezza, dolore) durante la progressione.'},

  // ---- PAVIMENTO PELVICO ----
  {id:'incontinenza-urinaria', category:'Pavimento pelvico', label:'Incontinenza urinaria da sforzo', text:
    'Valutazione e presa di coscienza della muscolatura del pavimento pelvico, esercizi di rinforzo specifico (tipo Kegel) progressivi.\nIntegrazione del lavoro perineale con il controllo posturale e respiratorio, eventuale biofeedback se disponibile.\nEducazione alla gestione delle pressioni intra-addominali nelle attività quotidiane e sportive.'},
  {id:'diastasi-addominale', category:'Pavimento pelvico', label:'Diastasi addominale post-parto', text:
    'Rieducazione del controllo motorio della parete addominale profonda (trasverso dell\'addome) in sinergia con pavimento pelvico e respirazione.\nProgressione graduale del rinforzo del core (dead bug, bird-dog), evitando manovre ad alta pressione intra-addominale nelle fasi iniziali.\nRipresa funzionale progressiva delle attività quotidiane e, se richiesto, sportive, monitorando la chiusura della diastasi.'},

  // ---- PEDIATRIA / SVILUPPO MOTORIO ----
  {id:'torcicollo-miogeno', category:'Pediatria e sviluppo motorio', label:'Torcicollo miogeno congenito', text:
    'Stretching passivo delicato del muscolo sternocleidomastoideo, stimolazione attiva della rotazione/inclinazione verso il lato non affetto tramite giochi posizionali.\nConsigli posturali ai genitori per le attività quotidiane (allattamento, gioco, sonno) per favorire il movimento simmetrico.\nMonitoraggio periodico dell\'evoluzione e dell\'eventuale plagiocefalia posizionale associata.'},
  {id:'ritardo-sviluppo-motorio', category:'Pediatria e sviluppo motorio', label:'Ritardo dello sviluppo motorio nel bambino', text:
    'Stimolazione delle tappe motorie in base all\'età (controllo del capo, rotolamento, posizione seduta, gattonamento, cammino) tramite attività ludiche mirate.\nCoinvolgimento attivo della famiglia nella pratica quotidiana delle proposte terapeutiche.\nMonitoraggio periodico dello sviluppo con eventuali rivalutazioni multidisciplinari se necessario.'},

  // ---- EQUILIBRIO E PROPRIOCEZIONE ----
  {id:'instabilita-cronica-caviglia', category:'Equilibrio e propriocezione', label:'Instabilità cronica di caviglia', text:
    'Rinforzo progressivo dei muscoli peronei ed evertori (elastico in eversione), propriocezione avanzata su superfici instabili e in condizioni dinamiche (occhi chiusi, doppio compito, tavoletta propriocettiva).\nLavoro su cambi di direzione e atterraggi controllati (drop landing con controllo), progressione verso gesti sport-specifici.\nValutazione di un\'eventuale instabilità meccanica persistente (per cui considerare ortesi o approfondimento specialistico).'},
  {id:'rieducazione-equilibrio-generale', category:'Equilibrio e propriocezione', label:'Deficit di equilibrio / rischio cadute (non vestibolare)', text:
    'Valutazione multifattoriale del rischio di caduta (forza, equilibrio, vista, ambiente domestico).\nEsercizi di equilibrio statico (tandem stance) e dinamico progressivi (cammino su linea, ostacoli bassi), rinforzo della muscolatura degli arti inferiori (squat, step-up).\nAdattamento dell\'ambiente domestico ed educazione alla sicurezza nelle attività quotidiane.'},
  {id:'sublussazione-rotula', category:'Equilibrio e propriocezione', label:'Sublussazione rotulea / instabilità femoro-rotulea', text:
    'Rinforzo del VMO (terminal knee extension, leg extension in ultimo arco) e della catena cinetica prossimale (glutei: clamshell, ponte monopodalico) per il controllo dell\'allineamento del ginocchio.\nEsercizi di controllo motorio in catena chiusa (mini-squat, step-down) monitorando il tracking rotuleo, propriocezione su superficie instabile.\nProgressione graduale verso corsa, cambi di direzione e gesto sportivo, eventuale bendaggio/tutore funzionale nella fase di ritorno all\'attività.'},
]
